// OfficialPageService — auto-generated public official profiles from jurisdiction config
// (jurisdiction-data leaders today; district MLA catalog later). Unclaimed seats are always
// public; no viewer gate. Unknown handles → 404 (not 403).

import { jurisdictions } from "@oursay/jurisdiction-data";
import type { JurisdictionConfig } from "@oursay/public-record";
import { ServiceError } from "../errors.js";
import { normalizeHandle } from "../helpers/handle.js";

export interface OfficialPageDto {
  name: string;
  /** Wire handle without the leading `@`. */
  handle: string;
  /** Display role line, e.g. "Premier · Alberta". */
  role: string;
  jurisdictionId: string;
  jurisdictionLabel: string;
  /** Null for jurisdiction-wide leaders (premier, stewards). */
  districtSlug: string | null;
  claimed: boolean;
  bio: string;
  bioAutoGenerated: boolean;
  /** Populated once the seat is claimed; empty while unclaimed. */
  posts: unknown[];
  activity: unknown[];
  mentions: unknown[];
}

export interface OfficialPageServiceDeps {
  jurisdictions?: JurisdictionConfig[];
}

/** Demo claim state until the claim flow lands — oursay claimed, premier not. */
const CLAIMED_HANDLES = new Set(["oursay"]);

function autoBio(name: string): string {
  return `This profile is generated from public record. ${name} has not endorsed this platform and may not be aware of this profile.`;
}

function claimedBio(jurisdiction: JurisdictionConfig): string {
  if (jurisdiction.id === "oursay-global") {
    return "Platform stewards for OurSay Global — governance updates, feature polls, and community consultation.";
  }
  return "";
}

function roleForLeader(j: JurisdictionConfig): string {
  const label = j.label ?? j.id;
  if (j.level === "provincial") return `Premier · ${label}`;
  if (j.id === "oursay-global") return `Platform stewards · ${label}`;
  return `Leader · ${label}`;
}

export class OfficialPageService {
  private readonly byHandle: Map<
    string,
    { jurisdiction: JurisdictionConfig; leader: { name: string; handle: string } }
  >;

  constructor(deps: OfficialPageServiceDeps = {}) {
    this.byHandle = new Map();
    for (const j of deps.jurisdictions ?? jurisdictions) {
      if (!j.leader) continue;
      const wire = normalizeHandle(j.leader.handle);
      if (!wire) continue;
      this.byHandle.set(wire, { jurisdiction: j, leader: j.leader });
    }
  }

  getPage(handleRaw: string): OfficialPageDto {
    const handle = normalizeHandle(handleRaw);
    if (!handle) throw new ServiceError("not_found", "official not found");
    const entry = this.byHandle.get(handle);
    if (!entry) throw new ServiceError("not_found", "official not found");

    const { jurisdiction, leader } = entry;
    const wire = leader.handle.replace(/^@/, "");
    const claimed = CLAIMED_HANDLES.has(handle);
    return {
      name: leader.name,
      handle: wire,
      role: roleForLeader(jurisdiction),
      jurisdictionId: jurisdiction.id,
      jurisdictionLabel: jurisdiction.label ?? jurisdiction.id,
      districtSlug: null,
      claimed,
      bio: claimed ? claimedBio(jurisdiction) : autoBio(leader.name),
      bioAutoGenerated: !claimed,
      posts: [],
      activity: [],
      mentions: [],
    };
  }
}
