// OfficialPageService — public official seat profiles from geo.official_seats (ingested with
// boundaries) with a file-catalog fallback when the DB roster is empty.

import {
  allOfficialSeats,
  isSeatClaimed,
  seatDisplayHandle,
  seatTitleFor,
  type OfficialSeatRecord,
} from "@oursay/jurisdiction-data";
import type { GeoStore, OfficialSeatRow } from "@oursay/geo";
import { ServiceError } from "../errors.js";
import { normalizeHandle } from "../helpers/handle.js";
import type { ProfilePageService, ProfileSupportDto } from "./profile-page.service.js";
import type { ApiViewer } from "./viewer-context.service.js";

export interface OfficialPageDto {
  /** Seat title, e.g. "Alberta Premier" or "District MLA". */
  seatTitle: string;
  /** Current office holder name from public record. */
  representativeName: string;
  /** @deprecated Use representativeName — kept for response compat. */
  name: string;
  /** Public handle: user handle when claimed, seat handle when unclaimed. */
  handle: string;
  /** Stable seat handle (always present). */
  seatHandle: string;
  /** Display role line, e.g. "Premier · Alberta" or "MLA · Edmonton-Strathcona". */
  role: string;
  jurisdictionId: string;
  jurisdictionLabel: string;
  districtSlug: string | null;
  claimed: boolean;
  claimedUserHandle: string | null;
  leaderRole?: string | null;
  bio: string;
  bioAutoGenerated: boolean;
  ageLabel?: string;
  support?: ProfileSupportDto;
  posts: unknown[];
  activity: unknown[];
  mentions: unknown[];
}

export interface OfficialPageServiceDeps {
  geoStore?: GeoStore;
  seats?: OfficialSeatRecord[];
  profilePageService?: ProfilePageService;
}

function autoBio(name: string): string {
  return `This profile is generated from public record. ${name} has not endorsed this platform and may not be aware of this profile.`;
}

function claimedBio(jurisdictionId: string): string {
  if (jurisdictionId === "oursay-global") {
    return "Platform leadership for Oursay Global — governance updates, feature polls, and community consultation.";
  }
  return "";
}

function jurisdictionLabelFor(jurisdictionId: string): string {
  if (jurisdictionId === "ab-ca-gov") return "Alberta";
  if (jurisdictionId === "oursay-global") return "OurSay Global";
  return jurisdictionId;
}

function mapFileSeat(seat: OfficialSeatRecord): OfficialPageDto {
  const claimed = isSeatClaimed(seat);
  const claimedUserHandle = seat.claimedUserHandle?.replace(/^@/, "").trim() ?? null;
  const seatTitle = seat.title ?? seatTitleFor(seat);
  return {
    seatTitle,
    representativeName: seat.name,
    name: seat.name,
    handle: seatDisplayHandle(seat),
    seatHandle: seat.seatHandle,
    role: seat.role,
    jurisdictionId: seat.jurisdictionId,
    jurisdictionLabel: jurisdictionLabelFor(seat.jurisdictionId),
    districtSlug: seat.districtSlug,
    claimed,
    claimedUserHandle,
    leaderRole: seat.leaderRole ?? null,
    bio: claimed ? claimedBio(seat.jurisdictionId) : autoBio(seat.name),
    bioAutoGenerated: !claimed,
    posts: [],
    activity: [],
    mentions: [],
  };
}

function mapDbSeat(row: OfficialSeatRow): OfficialPageDto {
  const claimedUserHandle = row.claimedUserHandle?.replace(/^@/, "").trim() ?? null;
  const claimed = Boolean(claimedUserHandle);
  return {
    seatTitle: row.title,
    representativeName: row.representativeName,
    name: row.representativeName,
    handle: claimed ? claimedUserHandle! : row.seatHandle,
    seatHandle: row.seatHandle,
    role: row.role,
    jurisdictionId: row.jurisdictionId,
    jurisdictionLabel: jurisdictionLabelFor(row.jurisdictionId),
    districtSlug: row.districtSlug,
    claimed,
    claimedUserHandle,
    leaderRole: row.leaderRole,
    bio: claimed ? claimedBio(row.jurisdictionId) : autoBio(row.representativeName),
    bioAutoGenerated: !claimed,
    posts: [],
    activity: [],
    mentions: [],
  };
}

export class OfficialPageService {
  private readonly geoStore?: GeoStore;
  private readonly profilePageService?: ProfilePageService;
  private readonly bySeatHandle: Map<string, OfficialSeatRecord>;
  private readonly byClaimedUserHandle: Map<string, OfficialSeatRecord>;

  constructor(deps: OfficialPageServiceDeps = {}) {
    this.geoStore = deps.geoStore;
    this.profilePageService = deps.profilePageService;
    this.bySeatHandle = new Map();
    this.byClaimedUserHandle = new Map();
    for (const seat of deps.seats ?? allOfficialSeats()) {
      this.bySeatHandle.set(seat.seatHandle, seat);
      const claimed = seat.claimedUserHandle?.replace(/^@/, "").trim();
      if (claimed) this.byClaimedUserHandle.set(claimed, seat);
    }
  }

  async getPage(handleRaw: string, viewer?: ApiViewer): Promise<OfficialPageDto> {
    const handle = normalizeHandle(handleRaw);
    if (!handle) throw new ServiceError("not_found", "official not found");

    let page: OfficialPageDto | null = null;

    if (this.geoStore) {
      const dbSeat =
        (await this.geoStore.getOfficialSeatByHandle(handle)) ??
        (await this.geoStore.getOfficialSeatByClaimedUserHandle(handle));
      if (dbSeat) page = mapDbSeat(dbSeat);
    }

    if (!page) {
      const fileSeat =
        this.bySeatHandle.get(handle) ?? this.byClaimedUserHandle.get(handle) ?? null;
      if (!fileSeat) throw new ServiceError("not_found", "official not found");
      page = mapFileSeat(fileSeat);
    }

    if (page.claimed && page.claimedUserHandle && this.profilePageService && viewer) {
      return this.enrichClaimed(page, viewer);
    }
    return page;
  }

  private async enrichClaimed(page: OfficialPageDto, viewer: ApiViewer): Promise<OfficialPageDto> {
    const handle = page.claimedUserHandle!;
    try {
      const [header, posts, activity, mentions] = await Promise.all([
        this.profilePageService!.getHeader(handle, viewer),
        this.profilePageService!.listPosts(handle, viewer, { limit: 100 }),
        this.profilePageService!.listActivity(handle, viewer, { limit: 100 }),
        this.profilePageService!.listMentions(handle, viewer, { limit: 100 }),
      ]);
      return {
        ...page,
        bio: header.bio || page.bio,
        bioAutoGenerated: !header.bio,
        ageLabel: header.ageLabel,
        support: header.support,
        posts: posts.items,
        activity: activity.items,
        mentions: mentions.items,
      };
    } catch (err) {
      if (err instanceof ServiceError && err.code === "not_found") return page;
      throw err;
    }
  }
}
