"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { BadgeCheck, IdCardLanyard, User } from "lucide-react";
import { getOfficialProfile, type OfficialProfile } from "@/lib/api/official";
import { isMockOnly } from "@/lib/api/client";
import {
  Avatar,
  Button,
  FeedCard,
  ProfileSupportBar,
  VerificationPill,
} from "@/components";
import {
  ACTIVITY_REACTION_TONE,
  REACTION_GLYPH,
  activityRowGlyph,
} from "@/components/content";
import {
  authorPath,
  districtPath,
  personaHintPath,
  postPath,
  postPathForId,
  profilePath,
} from "@/lib/routes";
import { districtName } from "@/lib/mock";
import { useApp } from "@/lib/state";
import type { ActivityKind } from "@/lib/types";
import { DEFERRED_CLAIM_PROFILE, DEFERRED_EDIT_HISTORY, DEFERRED_MENTIONS } from "@/lib/api/deferred";
import { recordShareTarget } from "@/lib/share";

type Tab = "posts" | "activity" | "mentions";

function activityToRecordId(kind: ActivityKind): string {
  if (kind === "petition") return "pet-wei-path";
  if (kind === "poll") return "poll-ableg-budget";
  return "stmt-hana-ravine";
}

/**
 * Official seat profile — auto-generated from public record (docs/11-USER-FLOWS §7.1).
 * Presents the office seat first; the current holder is a secondary link when claimed.
 */
export function OfficialView({ handle }: { handle: string }) {
  const app = useApp();
  const { setPageJurisdiction } = app;
  const router = useRouter();
  const [profile, setProfile] = useState<OfficialProfile | null | undefined>();
  const [tab, setTab] = useState<Tab>("posts");

  useEffect(() => {
    setPageJurisdiction(null);
  }, [setPageJurisdiction]);

  useEffect(() => {
    getOfficialProfile(handle).then(setProfile);
  }, [handle]);

  const selectTab = (t: Tab) => {
    if (t === "mentions" && !isMockOnly()) {
      app.notify(DEFERRED_MENTIONS);
      return;
    }
    setTab(t);
  };

  if (profile === undefined) {
    return <p className="p-6 text-center text-sm text-muted">Loading…</p>;
  }
  if (profile === null) {
    return <p className="p-6 text-center text-sm text-muted">Official profile not found.</p>;
  }

  const verified = app.effectiveVerified;
  const { profileTypes } = app.state;
  const posts = profile.posts.filter(
    (p) => profileTypes.includes(p.kind as ActivityKind) && p.tier >= verified,
  );
  const activity = profile.activity.filter((a) => profileTypes.includes(a.kind));
  const support = profile.support ?? {
    agrees: 0,
    disagrees: 0,
    statements: 0,
    comments: 0,
  };
  const showSupport = support.agrees + support.disagrees > 0;
  const claimedUserHandle = profile.claimedUserHandle ?? profile.handle;

  const representativeRow = profile.claimed ? (
    <button
      type="button"
      onClick={() => router.push(profilePath(claimedUserHandle))}
      className="flex min-w-0 max-w-full items-center gap-1.5 text-left text-xs font-medium text-brand-700 hover:text-brand-800"
    >
      <User size={13} className="shrink-0" aria-hidden />
      <span className="truncate underline underline-offset-2">
        {profile.representativeName}
      </span>
    </button>
  ) : (
    <p className="flex min-w-0 max-w-full items-center gap-1.5 text-xs italic text-muted">
      <User size={13} className="shrink-0" aria-hidden />
      <span className="truncate">{profile.representativeName}</span>
    </p>
  );

  return (
    <div className="space-y-1 p-3">
      <header className="rounded-xl border border-border bg-surface px-3 pt-3 pb-3">
        <div className="flex items-center gap-3">
          {profile.claimed ? (
            <Avatar
              name={profile.representativeName}
              seed={claimedUserHandle}
              size="lg"
            />
          ) : (
            <span
              className="inline-flex size-13 shrink-0 items-center justify-center rounded-full bg-brand-300"
              aria-hidden
            >
              <IdCardLanyard size={28} className="text-ink" />
            </span>
          )}
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2">
              <p className="truncate font-bold text-ink">{profile.role}</p>
              <VerificationPill tier={3} align="right" />
            </div>
            {representativeRow}
          </div>
        </div>

        {profile.bio ? (
          <p
            className={`mt-3 text-center text-sm text-ink-soft ${
              profile.bioAutoGenerated ? "italic" : ""
            }`}
          >
            {profile.bio}
          </p>
        ) : null}

        {profile.claimed && showSupport ? (
          <div className="mt-3">
            <ProfileSupportBar
              {...support}
              ageLabel={profile.ageLabel ?? ""}
              showReactions
            />
          </div>
        ) : null}

        {!profile.claimed ? (
          <div className="mt-4">
            <Button
              variant="primary"
              size="sm"
              fullWidth
              icon={BadgeCheck}
              onClick={() => app.notify(DEFERRED_CLAIM_PROFILE)}
            >
              Claim Profile
            </Button>
          </div>
        ) : null}
      </header>

      <div className="flex gap-1 rounded-lg border border-border bg-surface-muted p-0.5">
        {(["posts", "activity", "mentions"] as Tab[]).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => selectTab(t)}
            className={`flex-1 rounded-md py-1 text-sm capitalize ${
              tab === t
                ? "font-semibold text-ink underline decoration-2 underline-offset-4"
                : "font-medium text-ink-soft"
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {tab === "posts" ? (
        <div className="max-h-[62vh] space-y-3 overflow-y-auto overscroll-auto pr-1 pb-1">
          {!profile.claimed ? (
            <p className="py-4 text-center text-sm text-muted">
              No posts yet — activity appears here after the office holder claims this profile.
            </p>
          ) : posts.length === 0 ? (
            <p className="py-4 text-center text-sm text-muted">No posts match the filters.</p>
          ) : (
            posts.map((item) => {
              const personaHint = personaHintPath(item.identity);
              return (
                <FeedCard
                  key={item.id}
                  item={{
                    ...item,
                    sig: app.petitionSigFor(item),
                    ...app.reactionCountsFor(item),
                  }}
                  viewer={app.viewer}
                  tierMin={verified}
                  resolveDistrict={districtName}
                  onAuthorClick={() =>
                    router.push(authorPath(item.identity, item.handle))
                  }
                  onPersonaClick={
                    personaHint ? () => router.push(personaHint) : undefined
                  }
                  onTitleClick={() => router.push(postPath(item.kind, item.id))}
                  onCommentsClick={() =>
                    router.push(postPath(item.kind, item.id, { comments: true }))
                  }
                  onShare={() => app.openShare(recordShareTarget(item))}
                  shareCount={app.shareCountFor(item.id)}
                  shared={app.hasShared(item.id)}
                  onReact={(dir) => app.react(item, dir)}
                  selectedReaction={app.reactionFor(item.id)}
                  selectedVote={app.voteFor(item.id)}
                  signedPetition={app.hasSignedPetition(item.id)}
                  onVote={(label) => app.votePoll(item, label)}
                  onSignPetition={() => app.signPetition(item)}
                  onEditsClick={() => app.notify(DEFERRED_EDIT_HISTORY)}
                  onDistrictClick={(s) => router.push(districtPath(s))}
                />
              );
            })
          )}
        </div>
      ) : null}

      {tab === "activity" ? (
        <ul className="max-h-[62vh] space-y-2 overflow-y-auto overscroll-auto pr-1 pb-1">
          {!profile.claimed ? (
            <p className="py-4 text-center text-sm text-muted">
              No activity yet — activity appears here after the office holder claims this profile.
            </p>
          ) : activity.length === 0 ? (
            <p className="py-4 text-center text-sm text-muted">No activity matches the filters.</p>
          ) : (
            activity.map((a, i) => {
              const glyph = activityRowGlyph(a);
              return (
                <li key={i}>
                  <button
                    type="button"
                    onClick={() =>
                      router.push(
                        postPathForId(a.recordId ?? activityToRecordId(a.kind)),
                      )
                    }
                    className="flex w-full items-start gap-3 rounded-lg border border-border bg-surface p-3 text-left hover:bg-surface-muted"
                  >
                    {glyph.type === "reaction" ? (
                      <span
                        aria-hidden
                        className={`mt-0.5 inline-flex size-4 shrink-0 items-center justify-center text-sm font-bold leading-none ${
                          glyph.alt
                            ? ACTIVITY_REACTION_TONE.alt
                            : ACTIVITY_REACTION_TONE.default
                        }`}
                      >
                        {REACTION_GLYPH[glyph.dir]}
                      </span>
                    ) : (
                      <glyph.icon
                        size={16}
                        className="mt-0.5 shrink-0 text-brand-600"
                        aria-hidden
                      />
                    )}
                    <span className="min-w-0 flex-1">
                      <span className="block text-sm text-ink">{a.text}</span>
                      <span className="block text-xs text-muted">{a.meta}</span>
                    </span>
                  </button>
                </li>
              );
            })
          )}
        </ul>
      ) : null}

      {tab === "mentions" ? (
        <ul className="max-h-[62vh] space-y-2 overflow-y-auto overscroll-auto pr-1 pb-1">
          {profile.mentions.length === 0 ? (
            <p className="py-4 text-center text-sm text-muted">No mentions yet.</p>
          ) : (
            profile.mentions.map((m, i) => (
              <li key={i} className="rounded-lg border border-border bg-surface">
                <div className="px-3 pt-3">
                  <button
                    type="button"
                    onClick={() => router.push(authorPath(m.identity, m.handle))}
                    className="text-sm font-semibold text-ink hover:underline"
                  >
                    {m.author}
                  </button>
                </div>
                <button
                  type="button"
                  onClick={() =>
                    router.push(postPathForId(m.recordId ?? "stmt-hana-ravine"))
                  }
                  className="block w-full px-3 pb-3 pt-0.5 text-left hover:bg-surface-muted"
                >
                  <span className="block text-sm text-ink-soft">{m.text}</span>
                  <span className="mt-0.5 block text-xs text-muted">{m.meta}</span>
                </button>
              </li>
            ))
          )}
        </ul>
      ) : null}
    </div>
  );
}
