import { getProfileByHandle, JUR_DATA } from "@/lib/mock";
import type {
  ActivityItem,
  MentionItem,
  ProfilePost,
  ProfileSupport,
} from "@/lib/types";
import { apiGet, isMockOnly } from "./client";
import { mapActivityItem, mapFeedItem } from "./map";

/** Auto-generated official seat page (jurisdiction leaders today). */
export interface OfficialProfile {
  name: string;
  handle: string;
  role: string;
  jurisdictionId: string;
  jurisdictionLabel: string;
  districtSlug: string | null;
  claimed: boolean;
  bio: string;
  bioAutoGenerated: boolean;
  posts: ProfilePost[];
  activity: ActivityItem[];
  mentions: MentionItem[];
  support?: ProfileSupport;
  ageLabel?: string;
}

const CLAIMED_HANDLES = new Set(["oursay"]);

function autoBio(name: string): string {
  return `This profile is generated from public record. ${name} has not endorsed this platform and may not be aware of this profile.`;
}

function claimedBio(id: string): string {
  if (id === "oursay-global") {
    return "Platform stewards for OurSay Global — governance updates, feature polls, and community consultation.";
  }
  return "";
}

function roleForJurisdiction(id: string, label: string, level: string): string {
  if (level === "province") return `Premier · ${label}`;
  if (id === "oursay-global") return `Platform stewards · ${label}`;
  return `Leader · ${label}`;
}

function isClaimedHandle(handle: string): boolean {
  return CLAIMED_HANDLES.has(handle);
}

function getOfficialMock(handleRaw: string): OfficialProfile | null {
  const needle = handleRaw.replace(/^@/, "").toLowerCase();
  for (const summary of Object.values(JUR_DATA)) {
    const leader = summary.leader;
    if (!leader.name.trim()) continue;
    const wire = leader.handle.replace(/^@/, "").toLowerCase();
    if (wire !== needle) continue;

    const claimed = isClaimedHandle(wire);
    const corpus = getProfileByHandle(wire);

    return {
      name: leader.name,
      handle: wire,
      role: roleForJurisdiction(summary.id, summary.name, summary.level),
      jurisdictionId: summary.id,
      jurisdictionLabel: summary.name,
      districtSlug: null,
      claimed,
      bio: claimed ? (corpus?.bio ?? claimedBio(summary.id)) : autoBio(leader.name),
      bioAutoGenerated: !claimed,
      posts: claimed ? (corpus?.posts ?? []) : [],
      activity: claimed ? (corpus?.activity ?? []) : [],
      mentions: corpus?.mentions ?? [],
      support: corpus?.support,
      ageLabel: corpus?.ageLabel,
    };
  }
  return null;
}

function mapOfficialProfile(raw: Record<string, unknown>): OfficialProfile {
  const posts = Array.isArray(raw.posts)
    ? raw.posts.map((row) => mapFeedItem(row as Record<string, unknown>))
    : [];
  const activity = Array.isArray(raw.activity)
    ? raw.activity.map((row) => mapActivityItem(row as Record<string, unknown>))
    : [];
  const mentions = Array.isArray(raw.mentions)
    ? (raw.mentions as MentionItem[])
    : [];

  return {
    name: String(raw.name),
    handle: String(raw.handle),
    role: String(raw.role),
    jurisdictionId: String(raw.jurisdictionId),
    jurisdictionLabel: String(raw.jurisdictionLabel),
    districtSlug: raw.districtSlug == null ? null : String(raw.districtSlug),
    claimed: Boolean(raw.claimed),
    bio: String(raw.bio),
    bioAutoGenerated: Boolean(raw.bioAutoGenerated),
    posts,
    activity,
    mentions,
  };
}

async function getOfficialLive(handleRaw: string): Promise<OfficialProfile | null> {
  const raw = await apiGet<Record<string, unknown>>(
    `/v1/public/officials/${encodeURIComponent(handleRaw.replace(/^@/, ""))}`,
  );
  return raw ? mapOfficialProfile(raw) : null;
}

/** Resolve an official seat page by reserved handle. Unknown → null (404 UI). */
export async function getOfficialProfile(handleRaw: string): Promise<OfficialProfile | null> {
  if (isMockOnly()) return getOfficialMock(handleRaw);
  return getOfficialLive(handleRaw);
}
