import { ALBERTA_RIDINGS } from "@/lib/mock/alberta-ridings";
import { getProfileByHandle, JUR_DATA } from "@/lib/mock";
import { claimedUserHandleForSeat } from "@/lib/official-seat";
import type {
  ActivityItem,
  MentionItem,
  ProfilePost,
  ProfileSupport,
} from "@/lib/types";
import { apiGet, isMockOnly } from "./client";
import { mapActivityItem, mapFeedItem } from "./map";

/** Auto-generated official seat page (jurisdiction leaders + district MLAs). */
export interface OfficialProfile {
  seatTitle: string;
  representativeName: string;
  name: string;
  handle: string;
  seatHandle: string;
  claimedUserHandle?: string | null;
  role: string;
  jurisdictionId: string;
  jurisdictionLabel: string;
  districtSlug: string | null;
  claimed: boolean;
  leaderRole?: string | null;
  bio: string;
  bioAutoGenerated: boolean;
  posts: ProfilePost[];
  activity: ActivityItem[];
  mentions: MentionItem[];
  support?: ProfileSupport;
  ageLabel?: string;
}

function autoBio(name: string): string {
  return `This profile is generated from public record. ${name} has not endorsed this platform and may not be aware of this profile.`;
}

function claimedBio(jurisdictionId: string): string {
  if (jurisdictionId === "oursay-global") {
    return "Platform leadership for Oursay Global — governance updates, feature polls, and community consultation.";
  }
  return "";
}

function roleForJurisdiction(id: string, label: string, level: string): string {
  if (level === "province") return `Premier · ${label}`;
  if (id === "oursay-global") return "Platform · Global";
  return `Leader · ${label}`;
}

function getOfficialMock(handleRaw: string): OfficialProfile | null {
  const needle = handleRaw.replace(/^@/, "").toLowerCase();

  for (const summary of Object.values(JUR_DATA)) {
    const leader = summary.leader;
    if (!leader?.name.trim()) continue;
    const seatHandle = leader.handle.replace(/^@/, "").toLowerCase();
    const claimedUserHandle = claimedUserHandleForSeat(seatHandle);
    const matches =
      needle === seatHandle || (claimedUserHandle != null && needle === claimedUserHandle);
    if (!matches) continue;

    const claimed = claimedUserHandle != null;
    const corpus = claimed ? getProfileByHandle(claimedUserHandle) : getProfileByHandle("premier");

    return {
      seatTitle: summary.id === "ab-ca-gov" ? "Alberta Premier" : "Platform · Global",
      representativeName: leader.name,
      name: leader.name,
      handle: claimed ? claimedUserHandle! : seatHandle,
      seatHandle,
      claimedUserHandle: claimed ? claimedUserHandle : null,
      role: roleForJurisdiction(summary.id, summary.name, summary.level),
      jurisdictionId: summary.id,
      jurisdictionLabel: summary.name,
      districtSlug: null,
      claimed,
      leaderRole: summary.leader.leaderRole ?? (summary.id === "oursay-global" ? "platform" : "premier"),
      bio: claimed ? (corpus?.bio ?? claimedBio(summary.id)) : autoBio(leader.name),
      bioAutoGenerated: !claimed,
      posts: claimed ? (corpus?.posts ?? []) : [],
      activity: claimed ? (corpus?.activity ?? []) : [],
      mentions: corpus?.mentions ?? [],
      support: claimed ? corpus?.support : undefined,
      ageLabel: claimed ? corpus?.ageLabel : undefined,
    };
  }

  for (const riding of ALBERTA_RIDINGS) {
    const seatHandle = riding.mla.seatHandle.toLowerCase();
    if (needle !== seatHandle) continue;
    return {
      seatTitle: "District MLA",
      representativeName: riding.mla.name,
      name: riding.mla.name,
      handle: seatHandle,
      seatHandle,
      claimedUserHandle: null,
      role: `MLA · ${riding.name}`,
      jurisdictionId: "ab-ca-gov",
      jurisdictionLabel: "Alberta",
      districtSlug: riding.slug,
      claimed: false,
      leaderRole: "mla",
      bio: autoBio(riding.mla.name),
      bioAutoGenerated: true,
      posts: [],
      activity: [],
      mentions: [],
    };
  }

  return null;
}

function mapOfficialProfile(raw: Record<string, unknown>): OfficialProfile {
  const posts = Array.isArray(raw.posts)
    ? raw.posts.map((row) => mapFeedItem(row as Record<string, unknown>))
    : [];
  const activity = Array.isArray(raw.activity)
    ? raw.activity.map((row) => mapActivityItem(row as Record<string, unknown>))
    : [];
  const mentions = Array.isArray(raw.mentions)
    ? (raw.mentions as MentionItem[])
    : [];

  const supportRaw = raw.support as Record<string, number> | undefined;

  return {
    seatTitle: String(raw.seatTitle ?? raw.role ?? "Official seat"),
    representativeName: String(raw.representativeName ?? raw.name),
    name: String(raw.name),
    handle: String(raw.handle),
    seatHandle: String(raw.seatHandle ?? raw.handle),
    claimedUserHandle:
      raw.claimedUserHandle == null ? null : String(raw.claimedUserHandle),
    role: String(raw.role),
    jurisdictionId: String(raw.jurisdictionId),
    jurisdictionLabel: String(raw.jurisdictionLabel),
    districtSlug: raw.districtSlug == null ? null : String(raw.districtSlug),
    claimed: Boolean(raw.claimed),
    leaderRole: raw.leaderRole == null ? null : String(raw.leaderRole),
    bio: String(raw.bio),
    bioAutoGenerated: Boolean(raw.bioAutoGenerated),
    ageLabel: raw.ageLabel == null ? undefined : String(raw.ageLabel),
    support: supportRaw
      ? {
          agrees: supportRaw.agrees ?? 0,
          disagrees: supportRaw.disagrees ?? 0,
          statements: supportRaw.statements ?? 0,
          comments: supportRaw.comments ?? 0,
        }
      : undefined,
    posts,
    activity,
    mentions,
  };
}

async function getOfficialLive(handleRaw: string): Promise<OfficialProfile | null> {
  const raw = await apiGet<Record<string, unknown>>(
    `/v1/public/officials/${encodeURIComponent(handleRaw.replace(/^@/, ""))}`,
  );
  return raw ? mapOfficialProfile(raw) : null;
}

/** Resolve an official seat page by seat handle or claimed user handle. Unknown → null (404 UI). */
export async function getOfficialProfile(handleRaw: string): Promise<OfficialProfile | null> {
  if (isMockOnly()) return getOfficialMock(handleRaw);
  return getOfficialLive(handleRaw);
}
