// Official profile page — jurisdiction leaders + district MLA seats from @oursay/jurisdiction-data.

import { expect } from "chai";
import { resetWorld, type World } from "./helpers/world.js";

async function official(w: World, handle: string) {
  return w.app.inject({
    method: "GET",
    url: `/v1/public/officials/${encodeURIComponent(handle)}`,
  });
}

describe("30 official page: jurisdiction leaders", () => {
  let w: World;
  beforeEach(async () => {
    w = await resetWorld();
  });

  it("returns the Alberta premier seat from Open North working file", async () => {
    const res = await official(w, "ab-premier");
    expect(res.statusCode).to.equal(200, res.body);
    const body = res.json() as Record<string, unknown>;
    expect(body.seatTitle).to.equal("Alberta Premier");
    expect(body.representativeName).to.equal("Danielle Smith");
    expect(body.handle).to.equal("ab-premier");
    expect(body.seatHandle).to.equal("ab-premier");
    expect(body.role).to.equal("Premier · Alberta");
    expect(body.jurisdictionId).to.equal("ab-ca-gov");
    expect(body.districtSlug).to.equal("brooks-medicine-hat");
    expect(body.claimed).to.equal(false);
    expect(body.claimedUserHandle).to.equal(null);
    expect(body.bioAutoGenerated).to.equal(true);
    expect(String(body.bio)).to.include("generated from public record");
  });

  it("returns an Alberta MLA seat by district short slug handle", async () => {
    const res = await official(w, "ab-edm_strth");
    expect(res.statusCode).to.equal(200, res.body);
    const body = res.json() as Record<string, unknown>;
    expect(body.seatTitle).to.equal("District MLA");
    expect(body.seatHandle).to.equal("ab-edm_strth");
    expect(body.districtSlug).to.equal("edmonton-strathcona");
    expect(body.role).to.equal("MLA · Edmonton-Strathcona");
    expect(body.claimed).to.equal(false);
  });

  it("returns the global platform seat and resolves claimed user handle", async () => {
    const bySeat = await official(w, "global-platform");
    expect(bySeat.statusCode).to.equal(200, bySeat.body);
    const seatBody = bySeat.json() as Record<string, unknown>;
    expect(seatBody.seatTitle).to.equal("Platform · Global");
    expect(seatBody.representativeName).to.equal("OurSay Stewards");
    expect(seatBody.jurisdictionId).to.equal("oursay-global");
    expect(seatBody.role).to.equal("Platform · Global");
    expect(seatBody.claimed).to.equal(true);
    expect(seatBody.handle).to.equal("oursay");
    expect(seatBody.claimedUserHandle).to.equal("oursay");
    expect(seatBody.bioAutoGenerated).to.equal(false);
    expect(seatBody.posts).to.be.an("array");
    expect(seatBody.activity).to.be.an("array");
    expect(seatBody.mentions).to.be.an("array");

    const byUser = await official(w, "oursay");
    expect(byUser.statusCode).to.equal(200, byUser.body);
    expect(byUser.json()).to.deep.equal(seatBody);
  });

  it("404s unknown official handles", async () => {
    const res = await official(w, "no-such-official");
    expect(res.statusCode).to.equal(404);
  });
});
