// Official profile page — jurisdiction leaders from @oursay/jurisdiction-data.

import { expect } from "chai";
import { resetWorld, type World } from "./helpers/world.js";

async function official(w: World, handle: string) {
  return w.app.inject({
    method: "GET",
    url: `/v1/public/officials/${encodeURIComponent(handle)}`,
  });
}

describe("30 official page: jurisdiction leaders", () => {
  let w: World;
  beforeEach(async () => {
    w = await resetWorld();
  });

  it("returns the Alberta premier from jurisdiction config", async () => {
    const res = await official(w, "premier");
    expect(res.statusCode).to.equal(200, res.body);
    const body = res.json() as Record<string, unknown>;
    expect(body.name).to.equal("Hon. A. Premier");
    expect(body.handle).to.equal("premier");
    expect(body.role).to.equal("Premier · Alberta");
    expect(body.jurisdictionId).to.equal("ab-ca-gov");
    expect(body.claimed).to.equal(false);
    expect(body.bioAutoGenerated).to.equal(true);
    expect(String(body.bio)).to.include("generated from public record");
  });

  it("returns OurSay stewards from jurisdiction config", async () => {
    const res = await official(w, "oursay");
    expect(res.statusCode).to.equal(200, res.body);
    const body = res.json() as Record<string, unknown>;
    expect(body.name).to.equal("OurSay Stewards");
    expect(body.jurisdictionId).to.equal("oursay-global");
    expect(body.role).to.equal("Platform stewards · OurSay Global");
    expect(body.claimed).to.equal(true);
    expect(body.bioAutoGenerated).to.equal(false);
    expect(body.posts).to.be.an("array");
    expect(body.activity).to.be.an("array");
    expect(body.mentions).to.be.an("array");
  });

  it("404s unknown official handles", async () => {
    const res = await official(w, "no-such-official");
    expect(res.statusCode).to.equal(404);
  });
});
