/**
 * Words excluded from persona display-name dictionaries.
 * Matched case-insensitively against unique-names-generator entries.
 *
 * Covers explicit sexual/bodily terms, identity/appearance insults, violent or
 * degrading adjectives, and a few awkward animal/name collisions (e.g. Fanny, Gay).
 */
export const PERSONA_NAME_BLOCKLIST: ReadonlySet<string> = new Set(
  [
    // Explicit / sexual / bodily (incl. innuendo in Adjective+Noun combos)
    "bare",
    "bloody",
    "bottom",
    "crude",
    "curved",
    "dirty",
    "excited",
    "fat",
    "filthy",
    "gay",
    "hot",
    "juicy",
    "moaning",
    "naked",
    "naughty",
    "oral",
    "ripe",
    "salty",
    "sexual",
    "spicy",
    "stiff",
    "sweet",
    "tender",
    "thick",
    "tight",
    "wet",

    // Body / appearance / identity
    "black",
    "blonde",
    "brown",
    "chubby",
    "dutch",
    "female",
    "latin",
    "male",
    "petite",
    "racial",
    "red",
    "scrawny",
    "skinny",
    "slim",
    "ugly",
    "ugliest",
    "white",
    "yellow",

    // Violent / dark / insulting / degrading
    "accused",
    "afraid",
    "ashamed",
    "bitter",
    "blind",
    "broken",
    "crazy",
    "creepy",
    "cruel",
    "damaged",
    "dead",
    "deaf",
    "dizzy",
    "drunk",
    "dull",
    "dying",
    "empty",
    "envious",
    "evil",
    "fatal",
    "fierce",
    "foolish",
    "frail",
    "furious",
    "greasy",
    "grim",
    "gross",
    "grubby",
    "grumpy",
    "guilty",
    "harsh",
    "hostile",
    "hurt",
    "ill",
    "illegal",
    "itchy",
    "jealous",
    "lazy",
    "lonely",
    "lost",
    "mad",
    "marxist",
    "mean",
    "mute",
    "nasty",
    "nervous",
    "nosy",
    "painful",
    "panicky",
    "passive",
    "poor",
    "puny",
    "ratty",
    "raw",
    "rotten",
    "rude",
    "scared",
    "scary",
    "selfish",
    "shocked",
    "shrill",
    "sick",
    "silly",
    "slimy",
    "sore",
    "soviet",
    "stingy",
    "stuck",
    "stupid",
    "tart",
    "tense",
    "testy",
    "tired",
    "toxic",
    "tragic",
    "unable",
    "unfair",
    "unhappy",
    "upset",
    "uptight",
    "useless",
    "vicious",
    "violent",
    "weak",
    "wee",
    "wicked",
    "worried",
    "wrong",
    "yucky",

    // Awkward animals / given names (second pool)
    "ape",
    "bass",
    "booby",
    "fanny",
    "pig",
    "randy",
    "tory",
    "willy",
  ].map((w) => w.toLowerCase()),
);

export function isBlockedPersonaWord(word: string): boolean {
  return PERSONA_NAME_BLOCKLIST.has(word.toLowerCase());
}
