// Public official profile routes — auto-generated seat pages from jurisdiction config.
// Unauthenticated; unknown handles → 404. Claim flow is a follow-on.

import type { FastifyInstance } from "fastify";
import type { Services } from "../../container.js";
import { errorSchema } from "../schemas.js";

const officialPageResponse = {
  type: "object",
  properties: {
    seatTitle: { type: "string" },
    representativeName: { type: "string" },
    name: { type: "string" },
    handle: { type: "string" },
    seatHandle: { type: "string" },
    role: { type: "string" },
    jurisdictionId: { type: "string" },
    jurisdictionLabel: { type: "string" },
    districtSlug: { type: ["string", "null"] },
    claimed: { type: "boolean" },
    claimedUserHandle: { type: ["string", "null"] },
    leaderRole: { type: ["string", "null"] },
    bio: { type: "string" },
    bioAutoGenerated: { type: "boolean" },
    posts: { type: "array", items: { type: "object", additionalProperties: true } },
    activity: { type: "array", items: { type: "object", additionalProperties: true } },
    mentions: { type: "array", items: { type: "object", additionalProperties: true } },
  },
  required: [
    "seatTitle",
    "representativeName",
    "name",
    "handle",
    "seatHandle",
    "role",
    "jurisdictionId",
    "jurisdictionLabel",
    "districtSlug",
    "claimed",
    "claimedUserHandle",
    "bio",
    "bioAutoGenerated",
    "posts",
    "activity",
    "mentions",
  ],
} as const;

export function registerPublicOfficialRoutes(app: FastifyInstance, services: Services): void {
  app.get(
    "/v1/public/officials/:handle",
    {
      schema: {
        tags: ["public"],
        summary: "Auto-generated official profile from jurisdiction config (unclaimed seat page)",
        params: {
          type: "object",
          properties: { handle: { type: "string" } },
          required: ["handle"],
        },
        response: { 200: officialPageResponse, 404: errorSchema },
      },
    },
    async (req) => {
      const { handle } = req.params as { handle: string };
      return services.officialPageService.getPage(handle);
    },
  );
}
